package co.miranext.nosql;

/**
 *
 */
public class ColumnExtra {

    //if its an insert and its an auto generated by db, then we will not include it in the statement
    public final static String AUTO = "auto:";

    private boolean isAuto = false;
    private String column;
    /**
     * We need to parse if there is an auto:
     *
     * @param column
     */
    public ColumnExtra(final String column) {

        if ( column.startsWith(AUTO)  ) {
            isAuto = true;
            this.column = column.substring(AUTO.length());
        } else {
            this.column = column;
        }
    }

    public boolean isAuto() {
        return isAuto;
    }

    public String getColumn() {
        return column;
    }

    public String toString() {
        return this.getColumn();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ColumnExtra)) return false;

        ColumnExtra that = (ColumnExtra) o;

        if (isAuto != that.isAuto) return false;
        if (column != null ? !column.equals(that.column) : that.column != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = (isAuto ? 1 : 0);
        result = 31 * result + (column != null ? column.hashCode() : 0);
        return result;
    }
}
