package co.miranext.docdb;

/**
 *
 */
public class ColumnExtra {

    //if its an insert and its an auto generated by db, then we will not include it in the statement
    public final static String AUTO = "auto:";

    private boolean isAuto = false;
    private String column;
    /**
     * We need to parse if there is an auto:
     *
     * @param column
     */
    public ColumnExtra(final String column) {

        if ( column.startsWith(AUTO)  ) {
            isAuto = true;
            this.column = column.substring(AUTO.length());
        } else {
            this.column = column;
        }
    }

    public boolean isAuto() {
        return isAuto;
    }

    public String getColumn() {
        return column;
    }
}
